-- Run after schema.sql inside a transaction that is always rolled back.
do $$ begin
 if exists(select 1 from auth.users where id in ('00000000-0000-4000-8000-000000000101','00000000-0000-4000-8000-000000000102')) then raise exception 'Fixture IDs already exist'; end if;
 if has_function_privilege('authenticated','public.refund_scan_credit(uuid,boolean)','execute') then raise exception 'Client can refund photo credits'; end if;
 if has_function_privilege('anon','public.refund_scan_credit(uuid,boolean)','execute') then raise exception 'Anonymous can refund credits'; end if;
 if has_function_privilege('authenticated','public.settle_analysis_request(uuid,uuid,boolean,jsonb,jsonb)','execute') then raise exception 'Client can settle credits'; end if;
end $$;
insert into auth.users(id,email) values('00000000-0000-4000-8000-000000000101','release-fixture-a@invalid.example'),('00000000-0000-4000-8000-000000000102','release-fixture-b@invalid.example');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000101',true);
do $$ declare q jsonb; remaining int; until_first timestamptz; user_a uuid:='00000000-0000-4000-8000-000000000101'; user_b uuid:='00000000-0000-4000-8000-000000000102'; request uuid:='00000000-0000-4000-8000-000000000201'; begin
 q:=public.reserve_analysis_request(request,'photo');
 if q->>'allowed'<>'true' then raise exception 'Reservation failed: %',q; end if;
 select free_scans_remaining into remaining from public.profiles where id=user_a;
 if remaining<>2 then raise exception 'Reservation did not consume exactly once'; end if;
 q:=public.reserve_analysis_request(request,'photo');
 if q->>'reason'<>'reserved' then raise exception 'In-flight retry was not recognized'; end if;
 if (select free_scans_remaining from public.profiles where id=user_a)<>2 then raise exception 'Retry charged twice'; end if;
 perform public.settle_analysis_request(user_a,request,false);
 perform public.settle_analysis_request(user_a,request,false);
 if (select free_scans_remaining from public.profiles where id=user_a)<>3 then raise exception 'Refund not exactly once'; end if;
 request:='00000000-0000-4000-8000-000000000202';
 perform public.reserve_analysis_request(request,'text');
 perform public.settle_analysis_request(user_a,request,true,'{"mealName":"fixture"}');
 q:=public.reserve_analysis_request(request,'text');
 if q->>'reason'<>'complete' or q->'response'->>'mealName'<>'fixture' then raise exception 'Completed result not replayed'; end if;
 request:='00000000-0000-4000-8000-000000000203';
 perform public.reserve_analysis_request(request,'photo');
 update public.analysis_requests set created_at=now()-interval '3 minutes' where user_id=user_a and request_id=request;
 perform public.recover_analysis_reservations();
 if (select free_scans_remaining from public.profiles where id=user_a)<>3 then raise exception 'Abandoned reservation not recovered'; end if;
 perform public.apply_revenuecat_event('fixture-purchase','INITIAL_PURCHASE','PRODUCTION',array[user_a],true,now()+interval '1 month',1000);
 update public.profiles set free_scans_remaining=60,text_included_remaining=90,photo_included_used_week=15,text_included_used_week=10 where id=user_a;
 q:=public.reconcile_expired_entitlement();
 if q->>'is_pro'<>'true' or (select free_scans_remaining from public.profiles where id=user_a)<>60 then raise exception 'Legacy reconciliation demoted a valid subscription'; end if;
 perform public.apply_revenuecat_event('fixture-renew','RENEWAL','PRODUCTION',array[user_a],true,now()+interval '2 months',2000);
 if (select free_scans_remaining from public.profiles where id=user_a)<>60 then raise exception 'Renewal refilled same week'; end if;
 perform public.apply_revenuecat_event('fixture-old-expire','EXPIRATION','PRODUCTION',array[user_a],false,now()-interval '1 day',500);
 if not (select is_pro from public.profiles where id=user_a) then raise exception 'Stale expiry revoked new subscription'; end if;
 perform public.apply_revenuecat_event('fixture-sandbox-expire','EXPIRATION','SANDBOX',array[user_a],false,now()-interval '1 day',3000);
 if not (select is_pro from public.profiles where id=user_a) then raise exception 'Sandbox revoked production subscription'; end if;
 -- An interrupted Pro week must retain its unused allowance when restored.
 perform public.apply_revenuecat_event('fixture-b-purchase','INITIAL_PURCHASE','SANDBOX',array[user_b],true,now()+interval '1 day',1000);
 perform set_config('request.jwt.claim.sub',user_b::text,true);
 q:=public.reserve_analysis_request('00000000-0000-4000-8000-000000000204','photo');
 if q->>'allowed'<>'true' then raise exception 'Pro fixture could not scan'; end if;
 perform public.settle_analysis_request(user_b,'00000000-0000-4000-8000-000000000204',true,'{}');
 q:=public.reserve_analysis_request('00000000-0000-4000-8000-000000000206','text');
 if q->>'allowed'<>'true' then raise exception 'Pro fixture could not assess food'; end if;
 perform public.settle_analysis_request(user_b,'00000000-0000-4000-8000-000000000206',true,'{}');
 perform public.apply_revenuecat_event('fixture-b-expire','EXPIRATION','SANDBOX',array[user_b],false,now()-interval '1 second',2000);
 if (select free_scans_remaining from public.profiles where id=user_b)>3 then raise exception 'Expired Pro kept an active allowance'; end if;
 perform public.apply_revenuecat_event('fixture-b-resubscribe','INITIAL_PURCHASE','SANDBOX',array[user_b],true,now()+interval '1 day',3000);
 q:=public.get_my_quota();
 if q->>'is_pro'<>'true' or (q->>'free_scans_remaining')::int<>74 or (q->>'text_included_remaining')::int<>99 then raise exception 'Resubscribed Pro lost unused allowance: %',q; end if;
 perform public.apply_revenuecat_event('fixture-b-resubscribe','INITIAL_PURCHASE','SANDBOX',array[user_b],true,now()+interval '1 day',3000);
 if (select free_scans_remaining from public.profiles where id=user_b)<>74 then raise exception 'Duplicate subscription inflated scans'; end if;
 q:=public.reserve_analysis_request('00000000-0000-4000-8000-000000000205','photo');
 if q->>'allowed'<>'true' or (q->>'photo_remaining')::int<>73 then raise exception 'Resubscribed Pro could not scan: %',q; end if;
 perform public.settle_analysis_request(user_b,'00000000-0000-4000-8000-000000000205',true,'{}');
 perform public.apply_revenuecat_event('fixture-b-renew','RENEWAL','SANDBOX',array[user_b],true,now()+interval '2 days',4000);
 if (select free_scans_remaining from public.profiles where id=user_b)<>73 then raise exception 'Renewal inflated same-week scans'; end if;
 update public.profiles set free_scans_remaining=0,photo_included_used_week=75 where id=user_b;
 perform public.apply_revenuecat_event('fixture-b-fully-used','RENEWAL','SANDBOX',array[user_b],true,now()+interval '3 days',4500);
 if (select free_scans_remaining from public.profiles where id=user_b)<>0 then raise exception 'A fully used Pro allowance was refilled'; end if;
 perform public.apply_revenuecat_event('fixture-b-final-expire','EXPIRATION','SANDBOX',array[user_b],false,now()-interval '1 second',5000);
 perform set_config('request.jwt.claim.sub',user_a::text,true);
 update public.profiles set subscription_expires_at=now()-interval '1 second',quota_week=current_date-14 where id=user_a;
 perform public.refresh_user_quota(user_a);
 if (select is_pro from public.profiles where id=user_a) or (select free_scans_remaining from public.profiles where id=user_a)<>3 then raise exception 'Expired subscription survived weekly reset'; end if;
 insert into public.promo_codes(code_hash,label,max_redemptions,grants_days,expires_at) values(encode(extensions.digest('FIXTURE-PROMO','sha256'),'hex'),'fixture',2,1,now()+interval '1 hour');
 q:=public.redeem_promo_code('FIXTURE-PROMO'); until_first:=(q->>'until')::timestamptz;
 update public.profiles set free_scans_remaining=10 where id=user_a;
 q:=public.redeem_promo_code('FIXTURE-PROMO');
 if (q->>'until')::timestamptz<>until_first or (select free_scans_remaining from public.profiles where id=user_a)<>10 then raise exception 'Repeat promo changed quota or expiry'; end if;
 perform public.apply_credit_purchase(user_a,'fixture-pack',25,0,false);
 perform public.apply_credit_purchase(user_a,'fixture-pack',25,0,false);
 if (select photo_purchased from public.profiles where id=user_a)<>25 then raise exception 'Pack granted twice'; end if;
 update public.profiles set photo_purchased=5 where id=user_a;
 perform public.apply_credit_purchase(user_a,'fixture-pack',25,0,true);
 perform public.apply_credit_purchase(user_a,'fixture-pack',25,0,true);
 if (select photo_purchased from public.profiles where id=user_a)<>0 or (select photo_credit_debt from public.profiles where id=user_a)<>20 then raise exception 'Refund debt not tracked exactly once'; end if;
 perform public.apply_credit_purchase(user_a,'fixture-refund-first',25,0,true);
 perform public.apply_credit_purchase(user_a,'fixture-refund-first',25,0,false);
 if (select photo_purchased from public.profiles where id=user_a)<>0 then raise exception 'Refund-before-purchase granted credits'; end if;
 perform public.apply_revenuecat_event('fixture-alias','INITIAL_PURCHASE','PRODUCTION',array[user_a,user_b],true,now()+interval '1 day',4000);
 if (select is_pro from public.profiles where id=user_b) then raise exception 'Alias granted two separate accounts'; end if;
end $$;
set local role authenticated;
do $$ begin
 if (select count(*) from public.profiles)<>1 then raise exception 'RLS exposes other accounts'; end if;
 begin
   perform public.refund_scan_credit('00000000-0000-4000-8000-000000000101',false);
   raise exception 'Authenticated refund was allowed';
 exception when insufficient_privilege then null; end;
end $$;
reset role;
delete from auth.users where id='00000000-0000-4000-8000-000000000101';
do $$ begin
 if exists(select 1 from public.profiles where id='00000000-0000-4000-8000-000000000101') or exists(select 1 from public.analysis_requests where user_id='00000000-0000-4000-8000-000000000101') then raise exception 'Account deletion did not cascade'; end if;
end $$;
